[package]
name = "components"
edition = "2021"
description = "Abstracted Components for the site"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
